<?php

namespace Database\Seeders;

use App\Models\JenisGelar;
use Illuminate\Database\Seeder;

class PenyeederJenisGelar extends Seeder
{
    public function run(): void
    {
        $daftarGelar = [
            // ========= KVT.Kom — Sarjana Terapan (8 Semester, 144 SKS) =========
            [
                'kode'            => 'KVT.Kom',
                'gelar_singkat'   => 'S.KVT.Kom',
                'nama'            => 'Komputer Virtual Terapan',
                'kategori'        => 'sarjana',
                'deskripsi'       => 'Gelar tertinggi Kampus Virtual. Kurikulum berbasis industri teknologi terkini — rekayasa perangkat lunak, keamanan siber, cloud computing, dan kecerdasan buatan.',
                'syarat'          => "✅ Lulus SMA/SMK/sederajat\n✅ Usia minimal 17 tahun\n✅ Akses internet stabil\n✅ Motivasi belajar tinggi",
                'prospek_karir'   => "💼 Software Engineer\n🔒 Cyber Security Analyst\n☁️ Cloud Architect\n📊 Data Scientist\n🚀 CTO / Tech Lead Startup",
                'durasi_bulan'    => 48,
                'sks_dibutuhkan'  => 144,
                'jumlah_semester' => 8,
                'warna'           => '#6366F1',
                'urutan'          => 1,
                'keunggulan'      => [
                    '🏆 Setara Sarjana Terapan (D4) — diakui industri',
                    '💡 70% Praktik, 30% Teori — langsung terapkan ilmu',
                    '🤝 Mentoring 1-on-1 dengan praktisi IT aktif',
                    '🗂️ Portfolio nyata: 5+ proyek industri',
                    '🌐 Komunitas alumni 500+ di seluruh Indonesia',
                    '📜 Sertifikat profesi terintegrasi (AWS, Google, dll)',
                    '🔄 Kurikulum update setiap semester',
                ],
                'mata_kuliah_inti' => [
                    'Matematika Diskrit & Logika Pemrograman',
                    'Algoritma & Struktur Data',
                    'Pemrograman Berorientasi Objek (Python/Java)',
                    'Basis Data & Perancangan Database',
                    'Rekayasa Perangkat Lunak',
                    'Pengembangan Aplikasi Web Full-Stack',
                    'Pengembangan Aplikasi Mobile (Flutter)',
                    'Jaringan Komputer & Keamanan Siber',
                    'Cloud Computing (AWS/GCP)',
                    'Kecerdasan Buatan & Machine Learning',
                    'UI/UX Design & Pengalaman Pengguna',
                    'Manajemen Proyek IT & Metodologi Agile',
                    'Proyek Akhir / Skripsi Terapan',
                ],
            ],

            // ========= VT.Kom — Vokasi (6 Semester, 120 SKS) =========
            [
                'kode'            => 'VT.Kom',
                'gelar_singkat'   => 'VT.Kom',
                'nama'            => 'Vokasi Teknologi Komputer',
                'kategori'        => 'sarjana',
                'deskripsi'       => 'Gelar vokasi berbasis praktik. Fokus pengembangan aplikasi web, mobile, dan data — siap kerja dalam 3 tahun.',
                'syarat'          => "✅ Lulus SMA/SMK/sederajat\n✅ Usia minimal 17 tahun\n✅ Minat di bidang teknologi",
                'prospek_karir'   => "🌐 Web Developer (Front/Back/Full-Stack)\n📱 Mobile Developer\n📊 Data Analyst\n🔧 Network Engineer\n🖥️ IT Support Senior",
                'durasi_bulan'    => 36,
                'sks_dibutuhkan'  => 120,
                'jumlah_semester' => 6,
                'warna'           => '#3B82F6',
                'urutan'          => 2,
                'keunggulan'      => [
                    '⚡ Siap kerja dalam 3 tahun',
                    '💻 80% praktik coding nyata',
                    '🏅 Sertifikat profesi (Google, Microsoft)',
                    '👔 Akses job fair eksklusif alumni',
                    '🎯 Kurikulum divalidasi perusahaan tech',
                ],
                'mata_kuliah_inti' => [
                    'Dasar Pemrograman (Python & JavaScript)',
                    'Pemrograman Web (HTML, CSS, JavaScript)',
                    'Framework Web Modern (React/Vue + Laravel)',
                    'Basis Data MySQL & NoSQL',
                    'Pengembangan API RESTful',
                    'Pengembangan Aplikasi Mobile (Flutter/React Native)',
                    'UI/UX Design & Figma',
                    'DevOps Dasar (Docker, CI/CD)',
                    'Analisis Data & Visualisasi',
                    'Proyek Industri (Internship)',
                ],
            ],

            // ========= VTA.Kom — Vokasi Administrasi (5 Semester, 108 SKS) =========
            [
                'kode'            => 'VTA.Kom',
                'gelar_singkat'   => 'VTA.Kom',
                'nama'            => 'Vokasi Teknologi Administrasi Komputer',
                'kategori'        => 'vokasi',
                'deskripsi'       => 'Kombinasi administrasi bisnis dan teknologi digital. Ideal untuk profesional perkantoran yang ingin naik level ke era digital.',
                'syarat'          => "✅ Lulus SMA/SMK/sederajat\n✅ Pengalaman kerja lebih diutamakan",
                'prospek_karir'   => "🖥️ IT Administrator\n⚙️ Systems Administrator\n📋 Digital Office Manager\n🗄️ Database Administrator",
                'durasi_bulan'    => 30,
                'sks_dibutuhkan'  => 108,
                'jumlah_semester' => 5,
                'warna'           => '#10B981',
                'urutan'          => 3,
                'keunggulan'      => [
                    '📆 Jadwal fleksibel (weekend & malam hari)',
                    '🏢 Cocok untuk karyawan yang bekerja penuh waktu',
                    '☁️ Fokus cloud office Microsoft 365 & Google Workspace',
                    '🔐 Otomasi proses bisnis & keamanan data',
                ],
                'mata_kuliah_inti' => [
                    'Microsoft Office 365 Lanjutan',
                    'Google Workspace & Kolaborasi Digital',
                    'Manajemen Database Perkantoran',
                    'Keamanan Informasi & Privasi Data',
                    'Otomasi Proses Bisnis (RPA)',
                    'Administrasi Jaringan & Cloud',
                    'Manajemen Konten Digital',
                    'Proyek Digitalisasi Kantor',
                ],
            ],

            // ========= V.Com — Vokasi Commerce (4 Semester, 96 SKS) =========
            [
                'kode'            => 'V.Com',
                'gelar_singkat'   => 'V.Com',
                'nama'            => 'Vokasi Commerce',
                'kategori'        => 'vokasi',
                'deskripsi'       => 'Gelar bisnis digital terapan. Kuasai e-commerce, pemasaran digital, dan kewirausahaan berbasis teknologi.',
                'syarat'          => "✅ Lulus SMA/SMK/sederajat\n✅ Semangat wirausaha tinggi",
                'prospek_karir'   => "🛒 E-Commerce Manager\n📢 Digital Marketing Specialist\n🎨 Content Creator Profesional\n🚀 Digital Entrepreneur",
                'durasi_bulan'    => 24,
                'sks_dibutuhkan'  => 96,
                'jumlah_semester' => 4,
                'warna'           => '#F59E0B',
                'urutan'          => 4,
                'keunggulan'      => [
                    '🛒 Langsung praktik jualan di marketplace',
                    '📊 Google Analytics & Meta Ads certified',
                    '🤝 Mentoring dari pengusaha digital sukses',
                    '💰 Program inkubasi startup mini',
                ],
                'mata_kuliah_inti' => [
                    'Dasar Kewirausahaan Digital',
                    'E-Commerce & Marketplace (Shopee/Tokopedia/Tiktok)',
                    'Digital Marketing & SEO',
                    'Copywriting & Konten Kreatif',
                    'Social Media Marketing & Influencer',
                    'Google Ads & Meta Ads',
                    'Analitik Bisnis & Google Analytics',
                    'Proyek Bisnis Digital',
                ],
            ],

            // ========= K1 — Diploma Level 1 (1 Semester, 18 SKS) =========
            [
                'kode'            => 'K1',
                'gelar_singkat'   => 'Komp.1',
                'nama'            => 'Kompeten Level 1 — Literasi Digital',
                'kategori'        => 'diploma',
                'deskripsi'       => 'Fondasi literasi digital untuk pemula. Dari nol hingga mahir menggunakan komputer dan internet untuk produktivitas sehari-hari.',
                'syarat'          => "✅ Tidak ada syarat khusus\n✅ Siapapun bisa mendaftar\n✅ Bisa baca & tulis",
                'prospek_karir'   => "💼 Admin Kantor Digital\n🖥️ Operator Komputer\n📱 Asisten Digital",
                'durasi_bulan'    => 3,
                'sks_dibutuhkan'  => 18,
                'jumlah_semester' => 1,
                'warna'           => '#EF4444',
                'urutan'          => 5,
                'keunggulan'      => [
                    '🆓 Tersedia jalur gratis bersyarat',
                    '📱 Bisa belajar dari smartphone',
                    '👨‍👩‍👧 Cocok untuk segala usia',
                    '⏱️ Selesai hanya 3 bulan',
                ],
                'mata_kuliah_inti' => [
                    'Pengenalan Komputer & Sistem Operasi',
                    'Internet & Browsing Aman',
                    'Email & Komunikasi Digital',
                    'Media Sosial Produktif',
                    'Keamanan Digital Dasar',
                    'Praktik Produktivitas Digital',
                ],
            ],

            // ========= K2 (2 Semester, 36 SKS) =========
            [
                'kode'            => 'K2',
                'gelar_singkat'   => 'Komp.2',
                'nama'            => 'Kompeten Level 2 — Produktivitas Digital',
                'kategori'        => 'diploma',
                'deskripsi'       => 'Kuasai tools produktivitas digital standar industri. Microsoft Office, Google Workspace, dan kolaborasi tim online.',
                'syarat'          => "✅ Setara kompetensi K1\n✅ Bisa mengoperasikan komputer dasar",
                'prospek_karir'   => "📋 Staff Administrasi\n🗂️ Data Entry Operator\n📊 Asisten Analis Data",
                'durasi_bulan'    => 6,
                'sks_dibutuhkan'  => 36,
                'jumlah_semester' => 2,
                'warna'           => '#F97316',
                'urutan'          => 6,
                'keunggulan'      => [
                    '📊 Sertifikat Microsoft Office Specialist',
                    '🔄 Kurikulum update setiap tahun',
                    '⚡ Langsung bisa diterapkan di pekerjaan',
                ],
                'mata_kuliah_inti' => [
                    'Microsoft Word Profesional',
                    'Microsoft Excel & Rumus Lanjutan',
                    'Microsoft PowerPoint & Presentasi',
                    'Google Docs, Sheets & Slides',
                    'Google Drive & Kolaborasi Tim',
                    'Manajemen Email & Kalender',
                    'Zoom & Tools Meeting Online',
                    'Praktik Administrasi Digital',
                ],
            ],

            // ========= K3 (3 Semester, 54 SKS) =========
            [
                'kode'            => 'K3',
                'gelar_singkat'   => 'Komp.3',
                'nama'            => 'Kompeten Level 3 — Desain & Kreativitas',
                'kategori'        => 'diploma',
                'deskripsi'       => 'Kuasai desain grafis digital dari Canva hingga Adobe. Cocok untuk konten kreator, marketer, dan siapapun yang ingin tampil profesional.',
                'syarat'          => "✅ Setara kompetensi K2\n✅ Familiar tools digital",
                'prospek_karir'   => "🎨 Graphic Designer\n📸 Fotografer Produk Digital\n🎬 Konten Kreator\n📢 Social Media Specialist",
                'durasi_bulan'    => 9,
                'sks_dibutuhkan'  => 54,
                'jumlah_semester' => 3,
                'warna'           => '#EAB308',
                'urutan'          => 7,
                'keunggulan'      => [
                    '🎨 Dari Canva hingga Adobe suite',
                    '📹 Video editing dasar termasuk',
                    '🏆 Portfolio desain siap pakai',
                ],
                'mata_kuliah_inti' => [
                    'Prinsip Desain Visual',
                    'Canva Pro & Template Design',
                    'Adobe Photoshop — Editing Foto',
                    'Adobe Illustrator — Desain Vektor',
                    'Branding & Identitas Visual',
                    'Desain Media Sosial',
                    'Dasar Videografi & Editing',
                    'Fotografi Produk & Layout',
                    'Portofolio & Presentasi Desain',
                ],
            ],

            // ========= K4 (4 Semester, 72 SKS) =========
            [
                'kode'            => 'K4',
                'gelar_singkat'   => 'Komp.4',
                'nama'            => 'Kompeten Level 4 — Pemrograman Dasar',
                'kategori'        => 'diploma',
                'deskripsi'       => 'Mulai coding dari nol. Python dan Web dasar untuk otomasi, analisis data sederhana, dan pengembangan aplikasi pertamamu.',
                'syarat'          => "✅ Setara kompetensi K3\n✅ Tidak perlu pengalaman coding",
                'prospek_karir'   => "👨‍💻 Junior Programmer\n🌐 Web Developer Pemula\n🤖 Automation Specialist\n📊 Junior Data Analyst",
                'durasi_bulan'    => 12,
                'sks_dibutuhkan'  => 72,
                'jumlah_semester' => 4,
                'warna'           => '#84CC16',
                'urutan'          => 8,
                'keunggulan'      => [
                    '🐍 Python — bahasa paling populer 2024',
                    '🌐 Web dasar HTML/CSS/JS',
                    '⚡ 4 mini-proyek nyata dalam kurikulum',
                    '🤖 Dasar otomasi & scripting',
                ],
                'mata_kuliah_inti' => [
                    'Logika & Algoritma Pemrograman',
                    'Python Dasar — Sintaks & Struktur',
                    'Python Menengah — OOP & Modul',
                    'Otomasi dengan Python (scripting)',
                    'HTML & CSS — Struktur Web',
                    'JavaScript Dasar — Interaktivitas',
                    'Git & Version Control',
                    'Proyek Web Sederhana',
                    'Pengantar Basis Data SQL',
                    'Mini Proyek Akhir',
                ],
            ],

            // ========= K5 (6 Semester, 90 SKS) =========
            [
                'kode'            => 'K5',
                'gelar_singkat'   => 'Komp.5',
                'nama'            => 'Kompeten Level 5 — Pengembang Aplikasi',
                'kategori'        => 'diploma',
                'deskripsi'       => 'Jadi pengembang aplikasi profesional. Mobile (Flutter), backend (Node.js/Laravel), dan database lanjutan. Setara D3.',
                'syarat'          => "✅ Setara kompetensi K4\n✅ Bisa membuat program Python sederhana",
                'prospek_karir'   => "📱 Mobile App Developer\n⚙️ Backend Developer\n🔗 Full-Stack Developer Junior\n🗄️ Database Engineer",
                'durasi_bulan'    => 18,
                'sks_dibutuhkan'  => 90,
                'jumlah_semester' => 6,
                'warna'           => '#06B6D4',
                'urutan'          => 9,
                'keunggulan'      => [
                    '📱 Flutter — satu kode untuk Android & iOS',
                    '⚙️ Backend API dengan Node.js & Laravel',
                    '🗄️ MySQL, PostgreSQL & MongoDB',
                    '🚀 Publikasi 2 aplikasi ke Play Store',
                ],
                'mata_kuliah_inti' => [
                    'Flutter & Dart — Dasar Pengembangan Mobile',
                    'Flutter Lanjutan — State Management',
                    'Node.js & Express — Backend API',
                    'Laravel Framework — Backend PHP',
                    'REST API & Autentikasi (JWT/OAuth)',
                    'Database Relasional Lanjutan',
                    'MongoDB & Database NoSQL',
                    'Testing & Debugging Aplikasi',
                    'Deployment & App Store Publishing',
                    'Proyek Aplikasi Mobile Full-Stack',
                ],
            ],

            // ========= K6 (8 Semester, 108 SKS) =========
            [
                'kode'            => 'K6',
                'gelar_singkat'   => 'Komp.6',
                'nama'            => 'Kompeten Level 6 — Cloud & DevOps Engineer',
                'kategori'        => 'diploma',
                'deskripsi'       => 'Puncak jalur diploma. Kuasai cloud architecture, DevOps, dan kepemimpinan tim teknis. Setara D4 — siap jadi Tech Lead.',
                'syarat'          => "✅ Setara kompetensi K5\n✅ Pengalaman membuat aplikasi",
                'prospek_karir'   => "☁️ Cloud Engineer (AWS/GCP)\n🔄 DevOps Engineer\n👨‍💼 Tech Lead\n🏗️ Solution Architect\n🛡️ Site Reliability Engineer",
                'durasi_bulan'    => 24,
                'sks_dibutuhkan'  => 108,
                'jumlah_semester' => 8,
                'warna'           => '#8B5CF6',
                'urutan'          => 10,
                'keunggulan'      => [
                    '☁️ AWS & GCP certified path',
                    '🐳 Docker & Kubernetes mastery',
                    '🔄 CI/CD pipeline automation',
                    '👥 Leadership & team management',
                    '🏆 Proyek industri skala enterprise',
                ],
                'mata_kuliah_inti' => [
                    'Cloud Computing AWS — Fundamentals',
                    'Cloud Computing GCP — Associate',
                    'Containerisasi dengan Docker',
                    'Orkestrasi Kubernetes',
                    'CI/CD Pipeline (GitHub Actions/Jenkins)',
                    'Infrastructure as Code (Terraform)',
                    'Monitoring & Logging (Grafana/Prometheus)',
                    'Keamanan Cloud & Zero Trust',
                    'Kepemimpinan Tim Teknis',
                    'Arsitektur Sistem Skala Besar',
                    'Proyek Enterprise Cloud Migration',
                    'Sertifikasi AWS / GCP Preparation',
                ],
            ],
        ];

        foreach ($daftarGelar as $gelar) {
            JenisGelar::updateOrCreate(
                ['kode' => $gelar['kode']],
                array_merge($gelar, ['aktif' => true])
            );
        }
    }
}
